services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./app:/code/app
      - ./data:/code/data
    env_file:
      - .env
